services:
  frontend:
    container_name: frontend
    restart: no
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/usr/src/frontend/src:ro
    environment:
      - VITE_API_HOST=localhost
      - VITE_API_PORT=5000
    depends_on:
      - goapi

  goapi:
    container_name: goapi
    restart: no
    build:
      context: ./backend-go
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend-go:/usr/src/backend-go
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      - TEST_DATABASE_URL=postgres://user:password@test_db:5432/test_db?sslmode=disable
      - CGO_ENABLED=0

  test_db:
    container_name: postgres_test
    restart: no
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - ./sql/create-test-tables.sql:/docker-entrypoint-initdb.d/create-test-tables.sql:ro
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_db"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

volumes:
  data: {}
